version: "3.8"
services:
  app:
    build: ./infra/php
    volumes:
      - ./backend:/work

  web:
    build: ./infra/nginx
    ports:
      - 10080:80
    volumes:
      - ./backend:/work

  # 追記
  db:
    ports:
      - 3306:3306
    build: ./infra/mysql
    volumes:
      - db-store:/var/lib/mysql

volumes:
  db-store:
