# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # Specify the version you desire here
      - image: circleci/php:7.4-fpm-buster
      - image: circleci/mysql:8.0
    environment:
      - DB_CONNECTION: circle_testing
    steps:
      - checkout
      - run:
          name: Update apt-get
          command: sudo apt-get update
      - run:
          name: Docker php extensions install
          command: sudo docker-php-ext-install pdo_mysql
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "backend/composer.json" }}
            - v1-dependencies-
      - run:
          name: Install PHP libraries
          working_directory: backend
          command: composer install -n --prefer-dist
      - save_cache:
          paths:
            - ./backend/vendor
          key: v1-dependencies-{{ checksum "backend/composer.json" }}
       - run:
         name: Run Artisan
         command: backend/php artisan config:clear
      - run:
          name: Run PHPUnit
          command: backend/vendor/bin/phpunit backend/tests/Feature/
