<?php

namespace Tests\Feature;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class ItemTest extends TestCase
{
    use RefreshDatabase;

    public function setUp():void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->seed('ItemsTableSeeder');
    }

    public function test_url_should_be_required()
    {
        $response = $this->post('/mypage/create', [
            'url' => '',
        ]);

        $response->assertSessionHasErrors([
            'url' => 'URLは必須です。',
        ]);
    }
}
